AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  newrelic-custom-event-loader
  
  Sample SAM Template for newrelic-custom-event-loader

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5


Parameters:
  NewRelicInsightsInsertKey:
    Type: String
  NewRelicAccountId:
    Type: String

Resources:
  TestStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name: test-stream
      ShardCount: 1

  KinesisToCustomEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kinesis-to-custom-event/
      Handler: kinesis-to-custom-event
      Runtime: go1.x
      Tracing: Active
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          NEW_RELIC_INSIGHTS_INSERT_KEY: !Ref NewRelicInsightsInsertKey
          NEW_RELIC_ACCOUNT_ID: !Ref NewRelicAccountId
      Events:
        HelloWorldStream:
          Type: Kinesis
          Properties:
            Stream: !GetAtt TestStream.Arn
            StartingPosition: LATEST
            BatchSize: 3

